# Generated by Django 2.0.7 on 2018-07-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180723_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartfurniture',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='warehousefurniture',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
