# Generated by Django 2.0.7 on 2018-07-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180723_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
